// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gestion_de_tareas.Data;

#nullable disable

namespace gestiondetareas.Migrations
{
    [DbContext(typeof(AgendaDBContext))]
    [Migration("20250325235025_AgregarUsuarios")]
    partial class AgregarUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("gestion_de_tareas.Data.Tarea", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Estado")
                    .IsRequired()
                    .HasColumnType("varchar(255)");

                b.Property<DateTime>("Fecha")
                    .HasColumnType("datetime");

                b.Property<TimeSpan>("HoraFin")
                    .HasColumnType("time");

                b.Property<TimeSpan>("HoraInicio")
                    .HasColumnType("time");

                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasColumnType("varchar(255)");

                b.HasKey("Id");

                b.ToTable("Tareas");
            });
#pragma warning restore 612, 618
        }
    }
}
